// src/components/PdfReaderPane.tsx
import Paper from '@mui/material/Paper'
import { useEffect, useRef } from 'react'
import {
  loadPdfDocument,
  renderPdfPage,
  type PdfPageRender,
} from '@/lib/pdfReader'

type PdfReaderPaneProps = {
  pdfUrl: string
  pageNumber: number
  onReady: (ready: boolean) => void
}

export function PdfReaderPane({
  pdfUrl,
  pageNumber,
  onReady,
}: PdfReaderPaneProps) {
  const hostRef = useRef<HTMLDivElement | null>(null)
  const pageRef = useRef<HTMLDivElement | null>(null)
  const canvasRef = useRef<HTMLCanvasElement | null>(null)
  const textLayerRef = useRef<HTMLDivElement | null>(null)
  const paintRef = useRef<PdfPageRender | null>(null)
  const resizeObserverRef = useRef<ResizeObserver | null>(null)
  const lastWidthRef = useRef(0)
  const onReadyRef = useRef(onReady)
  onReadyRef.current = onReady

  useEffect(() => {
    let disposed = false
    let paintSeq = 0

    function stopPaint() {
      paintRef.current?.cancel()
      paintRef.current = null
    }

    function stopResizeObserver() {
      resizeObserverRef.current?.disconnect()
      resizeObserverRef.current = null
      lastWidthRef.current = 0
    }

    async function paintPage() {
      const host = hostRef.current
      const canvas = canvasRef.current
      const textLayer = textLayerRef.current
      const pageNode = pageRef.current
      if (!host || !canvas || !textLayer || !pageNode || disposed) return

      const cssWidth = Math.floor(host.clientWidth)
      if (cssWidth < 32) return

      const seq = ++paintSeq
      stopPaint()
      onReadyRef.current(false)

      const doc = await loadPdfDocument(pdfUrl)
      if (disposed || seq !== paintSeq) return

      const task = renderPdfPage(doc, pageNumber, {
        canvas,
        textLayerEl: textLayer,
        pageEl: pageNode,
        cssWidth,
      })
      paintRef.current = task
      try {
        await task.promise
      } catch {
        // Cancelled or render error; readiness stays false
      }
      if (!disposed && seq === paintSeq && paintRef.current === task) {
        onReadyRef.current(true)
      }
    }

    function observeHost() {
      stopResizeObserver()
      const host = hostRef.current
      if (!host) return

      resizeObserverRef.current = new ResizeObserver(() => {
        const width = Math.floor(host.clientWidth)
        if (Math.abs(width - lastWidthRef.current) < 1) return
        lastWidthRef.current = width
        void paintPage()
      })
      resizeObserverRef.current.observe(host)
    }

    observeHost()
    void paintPage()

    return () => {
      disposed = true
      paintSeq += 1
      stopPaint()
      stopResizeObserver()
    }
  }, [pdfUrl, pageNumber])

  return (
    <Paper
      elevation={3}
      sx={{ mx: 'auto', maxWidth: 900, borderRadius: 1, overflow: 'hidden' }}
    >
      <div
        ref={hostRef}
        className="pdf-host"
        data-testid="pdf-host"
        style={{ width: '100%' }}
      >
        <div ref={pageRef} className="pdf-page">
          <canvas ref={canvasRef} />
          <div ref={textLayerRef} className="textLayer" />
        </div>
      </div>
    </Paper>
  )
}

// src/components/PdfReaderPane.vue
<script setup lang="ts">
import { nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import {
  loadPdfDocument,
  renderPdfPage,
  type PdfPageRender,
} from '@/lib/pdfReader'

const props = defineProps<{
  pdfUrl: string
  pageNumber: number
}>()

const emit = defineEmits<{
  ready: [value: boolean]
}>()

const hostEl = ref<HTMLElement | null>(null)
const pageEl = ref<HTMLElement | null>(null)
const canvasEl = ref<HTMLCanvasElement | null>(null)
const textLayerEl = ref<HTMLElement | null>(null)

let paint: PdfPageRender | null = null
let resizeObserver: ResizeObserver | null = null
let lastWidth = 0

function stopPaint() {
  paint?.cancel()
  paint = null
}

function stopResizeObserver() {
  resizeObserver?.disconnect()
  resizeObserver = null
  lastWidth = 0
}

async function paintPage() {
  const host = hostEl.value
  const canvas = canvasEl.value
  const textLayer = textLayerEl.value
  const pageNode = pageEl.value
  if (!host || !canvas || !textLayer || !pageNode) return

  const cssWidth = Math.floor(host.clientWidth)
  if (cssWidth < 32) return

  stopPaint()
  emit('ready', false)
  const task = renderPdfPage(await loadPdfDocument(props.pdfUrl), props.pageNumber, {
    canvas,
    textLayerEl: textLayer,
    pageEl: pageNode,
    cssWidth,
  })
  paint = task
  await task.promise
  if (paint === task) {
    emit('ready', true)
  }
}

function observeHost() {
  stopResizeObserver()
  const host = hostEl.value
  if (!host) return

  resizeObserver = new ResizeObserver(() => {
    const width = Math.floor(host.clientWidth)
    if (Math.abs(width - lastWidth) < 1) return
    lastWidth = width
    void paintPage()
  })
  resizeObserver.observe(host)
}

async function sync() {
  await nextTick()
  observeHost()
  await paintPage()
}

watch(
  () => [props.pdfUrl, props.pageNumber] as const,
  () => {
    void sync()
  },
)

onMounted(() => {
  void sync()
})

onUnmounted(() => {
  stopPaint()
  stopResizeObserver()
})
</script>

<template>
  <v-sheet elevation="3" rounded class="mx-auto pdf-sheet">
    <div ref="hostEl" class="pdf-host" data-testid="pdf-host">
      <div ref="pageEl" class="pdf-page">
        <canvas ref="canvasEl" />
        <div ref="textLayerEl" class="textLayer" />
      </div>
    </div>
  </v-sheet>
</template>

<style scoped>
.pdf-sheet {
  max-width: 900px;
}

.pdf-host {
  width: 100%;
}
</style>
