// src/components/ReaderPager.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'

defineProps<{
  page: number
  totalPages: number
  prevPage: number | null
  nextPage: number | null
  wide?: boolean
}>()

const emit = defineEmits<{
  go: [target: number]
}>()

const { t } = useI18n()
</script>

<template>
  <div
    class="d-flex align-center justify-space-between mx-auto mt-4 pager"
    :class="{ 'pager-wide': wide }"
  >
    <v-btn
      icon="mdi-chevron-left"
      variant="text"
      color="primary"
      size="large"
      :disabled="prevPage == null"
      :aria-label="t('reader.prevPage')"
      @click="prevPage != null && emit('go', prevPage)"
    />
    <span class="text-medium-emphasis text-body-2">
      {{ t('reader.pageOf', { page, total: totalPages }) }}
    </span>
    <v-btn
      icon="mdi-chevron-right"
      variant="text"
      color="primary"
      size="large"
      :disabled="nextPage == null"
      :aria-label="t('reader.nextPage')"
      @click="nextPage != null && emit('go', nextPage)"
    />
  </div>
</template>

<style scoped>
.pager {
  max-width: 720px;
}

.pager-wide {
  max-width: 900px;
}
</style>

// src/components/ReaderPager.tsx
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft'
import ChevronRightIcon from '@mui/icons-material/ChevronRight'
import Box from '@mui/material/Box'
import IconButton from '@mui/material/IconButton'
import Typography from '@mui/material/Typography'
import { useTranslation } from 'react-i18next'

type ReaderPagerProps = {
  page: number
  totalPages: number
  prevPage: number | null
  nextPage: number | null
  wide?: boolean
  onGo: (target: number) => void
}

export function ReaderPager({
  page,
  totalPages,
  prevPage,
  nextPage,
  wide = false,
  onGo,
}: ReaderPagerProps) {
  const { t } = useTranslation()

  return (
    <Box
      sx={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        mx: 'auto',
        mt: 2,
        maxWidth: wide ? 900 : 720,
      }}
    >
      <IconButton
        color="primary"
        size="large"
        disabled={prevPage == null}
        aria-label={t('reader.prevPage')}
        onClick={() => prevPage != null && onGo(prevPage)}
      >
        <ChevronLeftIcon />
      </IconButton>
      <Typography variant="body2" color="text.secondary">
        {t('reader.pageOf', { page, total: totalPages })}
      </Typography>
      <IconButton
        color="primary"
        size="large"
        disabled={nextPage == null}
        aria-label={t('reader.nextPage')}
        onClick={() => nextPage != null && onGo(nextPage)}
      >
        <ChevronRightIcon />
      </IconButton>
    </Box>
  )
}
